Make config run async
11ty/eleventy pull request #1429
Opened 2020-09-27 06:14 UTC by MadeByMike

This allows for acync config. Such as: 

```js
module.exports = async (eleventyConfig) => {
   const data = await something();
   eleventyConfig.doSomethingWith(data)
}
```

The main changes are to `cmd.js` and the main `Eleventy` class. A number of calls in main 11ty runner are now delayed until after the config has been initialised. Other significant changes include the way plugins are added. These are now also async so they are resisted and resolved when config is run. 

Finally the way the global template config is managed has changed. Previously this could be imported from `src/Config.js` into anywhere and this would work since it is global. Now, since config is async we need to ensure that it is passed explicitly to each classes that uses it after it has been initialised.

Because of this there were also significant changes to tests to ensure that the config has been initialised before tests that depend on it.

There are a few todos including:

- [ ] More tests of async config functionality
- [ ] Tests to ensure the merging of plugins always occurs in the order added

Throwing this up here for feedback and to test the CI. Since 11ty doesn't ship a lock file I sometimes get differences with the way prism does highlighting.

I think the passing around of `templateConfig` could be improved by adding a base class that sets and manages these global properties. Tests could then override this property for individual classes. Happy to consider these type of suggestions or for future improvement to 11ty in general.

2020-09-27 06:57 UTC, MadeByMike commented
Fixes: https://github.com/11ty/eleventy/issues/614

2020-09-28 02:43 UTC, MadeByMike commented
I've been testing this in a real setting today and I hit this:
```
(node:8341) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 afterBuild listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

I'm not sure if it is related to this change or not but it looks like then the config changes the `beforeBuild`  and `afterBuild` listeners is added each time.

We should test this... might be happening with the existing prod build.

2020-09-28 02:53 UTC, MadeByMike commented
I found a bug where changes to the `.md` files correctly trigger a rebuild but changes to `.njk` files trigger the watcher (and rebuild the file) but without the updated data. 

- I might need help tracking this one down... probably in `mergeConfig` ?

2020-10-05 23:00 UTC, MadeByMike commented
Tracked it down to this...

I kept `UserConfig` as a singleton however when the config functions are async they call reset on this in parallel and this is bad news bears. I'm not sure I'm getting the CS terminology 100% right here but it's still early and hopefully explaining myself well enough that you get what is going on.

2020-10-06 00:17 UTC, MadeByMike commented
Got it! The data is correct. I'd moved the initialization of the watcher until after the config was initialized because it needed the config in the constructor. However init is run on change so I ended up with a new browser-sync server instance every time files changed and thus... no reload. 

Fixed by changing the watcher constructor.

**Running this in my project now with no issues - will keep tracking but I think this might be ok now**


**On the other issue I noticed**
I'm 99% sure the `MaxListenersExceededWarning` is not related to this. It happens because when the config function is run, (every change) events are added and old events are never cleared. There are some other things that work like this too including `addGlobalData` (which does no harm and might even be good for fresh data) but also `addTemplateFormats` which adds duplicate entries to the internal array in the end I think it's de-duped but in a way this data is a very slow memory leak.

2020-10-06 22:00 UTC, MadeByMike commented
> I've been testing this in a real setting today and I hit this:
> 
> ```
> (node:8341) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 afterBuild listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
> ```

I think this was solved by ensuring the config init() was only called once

2020-10-16 17:39 UTC, zachleat requested changes
Really sorry to do this but adding config arguments to constructors isn’t likely ideal for future maintenance—can you rework those? 😭

2020-10-16 17:39 UTC, zachleat commented on src/TemplateConfig.js
> +    // Note for Mike: I'm delaying the processing of plugins until here.
Did you have your think here 😅

2020-10-26 21:12 UTC, MadeByMike commented on cmd.js
> +      // Async config is going to require everything inside init()
Moved everything that can be moved.

2020-11-23 15:54 UTC, mariusschulz commented
@zachleat @MadeByMike I love this change! It'll be super useful for all kinds of async tasks done during the config setup, e.g. using [Shiki](https://github.com/shikijs/shiki) (which requires async initialization) as a syntax highlighter.

Thanks for working on this! :)

2021-06-09 02:30 UTC, kruncher commented
This feature would be extremely useful for me too.

2021-06-21 22:43 UTC, AleksandrHovhannisyan commented
Agreed, this would be amazing! In particular, it would let you do really cool things like generating different favicon sizes at build time so that you don't have to do that with external tools. I don't think you can do this with the 11ty Image plugin unless you make it a shortcode since it's async.

2022-01-03 18:52 UTC, zachleat commented
Hey y’all, I feel bad about this but unfortunately (and this is entirely my fault) I need to close this one as stale. The timing ended up being really bad and the scope of this PR ended up being a huge contributor to its downfall, as I did a pretty sizable refactor of the configuration stuff shortly after this was opened.

Really sorry.

(Also cross linking to #2103)

2022-01-03 18:52 UTC, closed without merging

2022-01-03 18:57 UTC, zachleat commented
Another cross link to home base at https://github.com/11ty/eleventy/issues/614