Add flag to run event handlers sequentially
11ty/eleventy pull request #3423
Opened 2024-08-25 09:02 UTC by vrugtehagel

2024-08-30 21:55 UTC, zachleat reviewed
Looking great! I definitely don’t want to add a temporary CLI argument for this though—I think it’d be better to keep it as a Configuration API only.

2024-08-30 21:56 UTC, zachleat requested changes
I think just revert the changes in cmd.cjs and src/Eleventy.js and we’ll be good

2024-08-31 07:45 UTC, vrugtehagel commented
Alright, @zachleat - removed the CLI flag entirely and moved the `setEmitterMode` method to `UserConfig`. So essentially, now users would have the ability to do

```js
export default function(eleventyConfig){
    eleventyConfig.setEmitterMode('sequential');
    // or…
    eleventyConfig.events.setHandlerMode('sequential');
} 
```

Hypothetically, we can remove the former in favor of the latter, but perhaps it's nice to have this "top-level" method since we have it for almost everything else. Let me know what you think :)

2024-09-03 15:27 UTC, zachleat commented
@vrugtehagel yeah I think in docs we’ll lean towards only recommending the former method—thank you!

2024-09-03 15:28 UTC, zachleat approved these changes
LGTM thank you!

2024-09-03 15:30 UTC, merged

2024-09-03 15:30 UTC, zachleat commented
Shipping with 3.0.0-beta.2 and 3.0.0-alpha.19

2024-09-26 22:08 UTC, zachleat commented
Temporary docs preview deploying here: https://11ty-website-git-v3-11ty.vercel.app/docs/events/#emitter-modes